version: '3'

services:
  server:
    container_name: server_s15540
    build: server
    volumes:
      - ./server/:/node-app
    environment:
      NODE_ENV: development
    depends_on:
      - db
    links:
      - db
    ports:
      - '9000:9000'

  db:
    image: 'mongo'
    container_name: db_s15540
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
